### PR TITLE
optimizations

### PR DESCRIPTION
**Pull request by cscherrer**
Results for

```julia
const a = au"""(program
    (= GRID_SIZE 16)
    
    (object Particle (Cell 0 0 "blue"))

    (: particles (List Particle))
    (= particles 
         (initnext (list) 
         (updateObj (prev particles) (--> obj (Particle (uniformChoice (adjPositions (.. obj origin))))))))
    
    (on clicked (= particles (addObj (prev particles) (Particle (Position (.. click x) (.. click y))))))
)"""

@benchmark interpret_over_time(a, 4, [ (click=Autumn.AutumnStandardLibrary.Click(5,5),), empty_env(), (click=Autumn.AutumnStandardLibrary.Click(9,9),), empty_env()])
```

Before:
image

After:
image

### CODE REVIEW

**Comment by cscherrer** [comment]
Upudate:
image

**Comment by cscherrer** [comment]
image

**Comment by cscherrer** [comment]
image

**Comment by cscherrer** [comment]
image

**Comment by riadas** [comment]
Made a small change so that Autumn.jl still interfaces with [CausalDiscovery.jl](https://github.com/zenna/CausalDiscovery.jl), which contains the actual synthesis algorithm (realized the test suite in Autumn is actually pretty minimal, so I should add more to that too). To check for performance improvements in CausalDiscovery.jl, running the CISC benchmark program under "Quick Start" in the README should be enough. I just manually ran it a few times with the `master` and `cs-eachindex` branches of Autumn, and it looks like there's a 30+ second improvement on my machine (~95 seconds vs ~125 seconds originally). Hooray!

**Pull request merged**
